version: '3.4'

services:
  weathersiberiandata:
    image: weathersiberiandata:dev
    container_name: WeatherSiberianData
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WeatherSiberianData"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_weathersiberiandata$
    volumes:
      - C:\Users\arsic\OneDrive\Desktop\Projekat Jovana\Projekat\WeatherProject\WeatherSiberianData:/app
      - C:\Users\arsic\OneDrive\Desktop\Projekat Jovana\Projekat\WeatherProject:/src
      - C:\Users\arsic\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_weathersiberiandata$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_weathersiberiandata$ \"/app/bin/Debug/net5.0/WeatherSiberianData.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  weathersiberiansensor:
    image: weathersiberiansensor:dev
    container_name: WeatherSiberianSensor
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WeatherSiberianSensor"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_weathersiberiansensor$
    volumes:
      - C:\Users\arsic\OneDrive\Desktop\Projekat Jovana\Projekat\WeatherProject\WeatherSiberianSensor:/app
      - C:\Users\arsic\OneDrive\Desktop\Projekat Jovana\Projekat\WeatherProject:/src
      - C:\Users\arsic\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_weathersiberiansensor$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_weathersiberiansensor$ \"/app/bin/Debug/net5.0/WeatherSiberianSensor.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
